use std::fs;
use std::path::{Path, PathBuf};

/// Lowercase, alnum-and-dash only, no leading/trailing/duplicate dashes.
pub fn slugify(title: &str) -> String {
    let mut out = String::new();
    let mut last_dash = false;
    for c in title.to_lowercase().chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
            last_dash = false;
        } else if !last_dash && !out.is_empty() {
            out.push('-');
            last_dash = true;
        }
    }
    let trimmed = out.trim_end_matches('-').to_string();
    if trimmed.is_empty() {
        "skill".to_string()
    } else {
        trimmed
    }
}

fn unique_slug(title: &str, skills_dir: &Path) -> String {
    let base = slugify(title);
    let mut candidate = base.clone();
    let mut n = 2;
    while skills_dir.join(&candidate).exists() {
        candidate = format!("{base}-{n}");
        n += 1;
    }
    candidate
}

fn yaml_quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Drafts a SKILL.md from the accumulated evidence for a candidate and
/// writes it to `<skills_dir>/<slug>/SKILL.md`. Deliberately unpolished:
/// the description is a blunt "use when this matches" statement and the
/// body just lists the raw observed summaries — good enough to be useful
/// and honest about being auto-generated, not a substitute for a human
/// tightening the trigger condition once it's seen real (mis)fires.
pub fn draft_and_write(
    title: &str,
    summaries: &[(String, Option<String>)],
    reason: &str,
    skills_dir: &Path,
) -> anyhow::Result<(String, PathBuf)> {
    let slug = unique_slug(title, skills_dir);
    let dir = skills_dir.join(&slug);
    fs::create_dir_all(&dir)?;

    let description = format!(
        "Use when the situation matches: {title}. Auto-promoted by Myelin ({reason}) \
         after {} observation(s) — tighten this trigger if it fires too broadly, or too rarely.",
        summaries.len()
    );

    let mut body = format!(
        "# {title}\n\n_Auto-generated by Myelin — promoted via `{reason}`, from {} observation(s). \
         Review before trusting it blindly._\n\n## Observed steps\n\n",
        summaries.len()
    );
    for (i, (summary, project)) in summaries.iter().enumerate() {
        let proj_note = project
            .as_deref()
            .map(|p| format!(" (seen in {p})"))
            .unwrap_or_default();
        body.push_str(&format!("{}. {summary}{proj_note}\n", i + 1));
    }

    let content = format!(
        "---\nname: {slug}\ndescription: {}\n---\n\n{body}",
        yaml_quote(&description)
    );

    let path = dir.join("SKILL.md");
    fs::write(&path, content)?;
    Ok((slug, path))
}

/// Appends a correction directly into the live SKILL.md body — this is
/// what makes a promoted skill a living document instead of a one-shot
/// artifact: it accumulates real fixes at the point they're reported,
/// rather than needing a human to notice and edit the file.
pub fn append_correction(path: &Path, note: &str) -> anyhow::Result<()> {
    let mut content = fs::read_to_string(path)?;
    if !content.contains("\n## Corrections\n") {
        content.push_str("\n## Corrections\n\n");
    }
    let now = chrono::Utc::now().to_rfc3339();
    content.push_str(&format!("- ({now}) {note}\n"));
    fs::write(path, content)?;
    Ok(())
}
